import TopNav from "@/app/components/TopNav";
import "./globals.css";
import "bootstrap-material-design/dist/css/bootstrap-material-design.css";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Next full first",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <TopNav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
